server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        - id: member
          uri: lb://member
          predicates:
            - Path=/member/**
        - id: business
          uri: lb://business
          predicates:
            - Path=/business/**
        - id: batch
          uri: lb://batch
          predicates:
            - Path=/batch/**

logging:
  level:
    com.szx.train: debug
#    org.springframework.cloud.gateway: debug

szx:
  auth:
    exclude-paths:
      - /member/member/register
      - /member/member/code
      - /member/test
      - /member/admin/**
      - /business/test
      - /business/admin/**
      - /batch/test
      - /batch/admin/**




