server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: member
          uri: http://localhost:8081
          predicates:
            - Path=/member/**
        - id: business
          uri: http://localhost:8082
          predicates:
            - Path=/business/**

logging:
  level:
    com.szx.train: debug

szx:
  auth:
    exclude-paths:
      - /member/member/register
      - /member/member/code
      - /member/test
      - /business/test
      - /*/admin




