server:
  port: 8080

logging:
  level:
    com.szx.train: debug
#    org.springframework.cloud.gateway: debug

szx:
  auth:
    exclude-paths:
      - /member/member/register
      - /member/member/code
      - /member/test
      - /member/admin/**
      - /business/test
      - /business/admin/**
      - /batch/test
      - /batch/admin/**




