server:
  port: 8083
  servlet:
    context-path: /batch # 访问路径
spring:
  datasource:
    url: jdbc:mysql://192.168.100.128:3306/train-batch?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: train
    password: train

mybatis-plus:
  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   # 开发时建议开启看SQL
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
    default-executor-type: batch
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto
  mapper-locations: classpath*:mapper/**/*.xml


logging:
  level:
    com.szx.train: debug
    com.szx.train.business.mapper: trace

knife4j:
  enable: true                     # 开启 Knife4j 增强功能（必须）
  production: false                # false 开发环境，true 生产环境会禁用 UI
  setting:
    enableFooter: false            # 关闭底部版权信息
    enableSwaggerModels: true
    language: zh-CN                # 中文界面
  documents:
    - group: batch服务
      name: batch-api



